import '../styles/globals.css'
import { AppProps } from 'next/app'
import Head from "next/head";
import Header from '../components/header';
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient();

export default function App({ Component, pageProps }: AppProps) {
  return (
      <div>
        <Head>
          <title>Bin Blog</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/avatar.jpg" />
        </Head>
        <Header/>
          <QueryClientProvider client={queryClient}>
              <div className={"dark:bg-[#171717]"}>
                  <Component {...pageProps}/>
              </div>
          </QueryClientProvider>
      </div>
  )
}
